# Generated by Django 5.0.1 on 2024-01-30 05:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="updated_at",
        ),
    ]
