# Generated by Django 5.0.1 on 2024-02-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_blogpost_title_profile_userdetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="phone_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="email",
            field=models.CharField(max_length=50),
        ),
    ]
