# Generated by Django 5.0.1 on 2024-02-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_userdetails_phone_number_alter_userdetails_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="phone_number",
            field=models.IntegerField(max_length=50),
        ),
    ]
