# Generated by Django 5.0.1 on 2024-02-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_userdetails_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="phone_number",
            field=models.IntegerField(),
        ),
    ]
