# Generated by Django 5.0.1 on 2024-02-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_alter_userdetails_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="email",
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="user",
            field=models.CharField(max_length=50),
        ),
    ]
