# Generated by Django 5.0.1 on 2024-02-06 07:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_alter_userdetails_email_alter_userdetails_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdetails",
            name="user",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
        migrations.DeleteModel(
            name="UserDetails",
        ),
    ]
